### ISSUE TITLE
Code review for Prajwal

### ISSUE THREAD

**Issue by EthanWong2212** [AY2122S1-CS2113T-W12-1/tp#243]
@praj-bellakka
- [x] Consider shortening long comments to improve readability. Focus on the What and why rather than how.
![image](https://user-images.githubusercontent.com/68017484/139533510-79a7b11e-4380-4002-bd5e-a4a4565808dd.png)

- [x] Consider shortening the method through abstraction
![image](https://user-images.githubusercontent.com/68017484/139533597-558276ae-ef9b-4a2c-a1ab-e1cc98ab45cd.png)

**Comment by praj-bellakka** [comment]
Refactored and SLAPed in #353 and #358
