### ISSUE TITLE
[PE-D] Unclear error message with invalid find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-1/tp#267]
Entering an invalid find command returns an error message that may not be very readable for potential users of the app. An invalid command error may be more appropriate if you don't want to use an error-specific message to handle this.

Steps to reproduce: run `find /sks fries`

Expected: An error message more relevant to the error, or an invalid command error message

Actual:

![Screenshot 2021-10-29 at 5.01.11 PM.png](https://raw.githubusercontent.com/ptejasv/ped/main/files/0c866c21-8c8a-44f7-8018-7966244c83c8.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ptejasv/ped#6

**Comment by kengjit** [comment]
Changes has been made
