### ISSUE TITLE
[PE-D] Edit function is very confusing for user

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-1/tp#285]
Instructions are not clear, UI of app does not help, user guide does not give full instructions as well.

![image.png](https://raw.githubusercontent.com/qqkoh/ped/main/files/88f5cc61-4f8f-4292-9491-cd21606e5c97.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: qqkoh/ped#6

**Comment by kengjit** [comment]
Thank you for the feedback. I have made changes to the overall aesthetics.
