### ISSUE TITLE
[PE-D] edit entry does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-1/tp#303]
I am expected to see the name of entry 1 change to 'choco' but it does not change and the app prompt is confusing as well

![image.png](https://raw.githubusercontent.com/hozhenhong99/ped/main/files/42be3103-284a-408a-aa90-348269469473.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: hozhenhong99/ped#11

**Comment by kengjit** [comment]
Thank you for your feedback. The app is working as intended. 

In line 7, you were asked to select the food you would like to edit your entry to. If you would like to edit it to 'choco', instead of inputting '1', you could have inputted 0 and added a new food item "choco".
