### ISSUE TITLE
[PE-D] Accepts whole string when entering invalid MEALTIME during add

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-1/tp#314]
Steps to Reproduce:
1. Start tp.jar
2. Add a food with an invalid MEALTIME command

Expected:

Reject input, and reprompt

Actual:

![image.png](https://raw.githubusercontent.com/Kureans/ped/main/files/82d52b43-cfd9-406a-b39a-ddd7cb0f95ba.png)

(Accepts entire string, which may cause user to have to redelete and add)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Kureans/ped#7

**Comment by praj-bellakka** [comment]
This is a feature, not a bug as we are not checking for spelling mistakes
